INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES(1000, 'Commic');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES(2000, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES(3000, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES(1000, 'Teste de commic');
INSERT INTO SUPPLIER (ID, NAME) VALUES(2000, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES(1000, 'Panasonic', 1000,1000, 10, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES(2000, 'Amazon', 2000,2000, 5, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES(3000, 'A pedra preciosa', 1000,1000, 3, CURRENT_TIMESTAMP);